package app.books.tanga.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF265EA7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3D)
val md_theme_light_secondary = Color(0xFF00639B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCEE5FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D33)
val md_theme_light_tertiary = Color(0xFF944A00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC6)
val md_theme_light_onTertiaryContainer = Color(0xFF301400)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF001849)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF001849)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFEEF0FF)
val md_theme_light_inverseSurface = Color(0xFF002B75)
val md_theme_light_inversePrimary = Color(0xFFA8C8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF265EA7)
val md_theme_light_outlineVariant = Color(0xFFC4C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA8C8FF)
val md_theme_dark_onPrimary = Color(0xFF003062)
val md_theme_dark_primaryContainer = Color(0xFF00468A)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_secondary = Color(0xFF97CBFF)
val md_theme_dark_onSecondary = Color(0xFF003353)
val md_theme_dark_secondaryContainer = Color(0xFF004A76)
val md_theme_dark_onSecondaryContainer = Color(0xFFCEE5FF)
val md_theme_dark_tertiary = Color(0xFFFFB784)
val md_theme_dark_onTertiary = Color(0xFF4F2500)
val md_theme_dark_tertiaryContainer = Color(0xFF713700)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001849)
val md_theme_dark_onBackground = Color(0xFFDBE1FF)
val md_theme_dark_surface = Color(0xFF001849)
val md_theme_dark_onSurface = Color(0xFFDBE1FF)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF001849)
val md_theme_dark_inverseSurface = Color(0xFFDBE1FF)
val md_theme_dark_inversePrimary = Color(0xFF265EA7)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA8C8FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF0F4C90)


val TangaWhiteBackground = Color(0xFFF6F3F6)
val TangaBluePale = Color(0xFF115A8E)
val TangaBottomBarIconColorSelected = Color(0xFF0f4c90)
val TangaBottomBarIconColorSelected40PercentTransparent = Color(0x660f4c90)
val TangaBottomBarIconColorUnSelected = Color(0xFFafafaf)
val TangaBlueDark = Color(0xFF091A38)
val TangaBluePaleSemiTransparent = Color(0x80115A8E)
val TangaBluePaleSemiTransparent2 = Color(0x1A115A8E)
val TangaOrange = Color(0xFFFA974A)
val TangaOrangeTransparent = Color(0x33FA974A)
val Pink80 = Color(0xFFEFB8C8)
val TextBlackMate = Color(0xFF333333)
val TextGray = Color(0xFF8B8B8B)
val TangaLightBlue = Color(0xFF1F91DD)
val TangaLightGray = Color(0xFFBDBDBD)
val TangaLightGray2 = Color(0xFFA4A4A4)

/* Profile/Setting colors */
val ProfileYellow = Color(0xFFEFCC59)
val ProfileYellowBackground = Color(0xFFFCEFD0)
val ProfileGreen = Color(0xFF5AAF75)
val ProfileGreenBackground = Color(0xFFD4F4DC)
val ProfileRed = Color(0xFFD25F64)
val ProfileRedBackground = Color(0xFFFDD8D8)
val ProfilePurple = Color(0xFF5D62CD)
val ProfilePurpleBackground = Color(0xFFD7DAFE)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)