name: Auto Approve PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Approve for rygelouv
        if: ${{ github.actor == 'rygelouv' }}
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "PR automatically approved by auto-approve-action"
