# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      
      - name: Load Google Services file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -D > app/google-services.json
       # Execute unit tests
      
      - name: Unit Test with Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with: 
            api-level: 29
            script: ./gradlew jacocoTestReport
            #./gradlew createDebugCoverageReport:  

       # run: ./gradlew testDebugUnitTest

      - name: Run Kover
        run: ./gradlew koverXmlReportDebug

      - name: Generate report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: app/build/reports/coverage/androidTest/debug/connected/
         # path: app/build/test-results

#      - name: Download Test Reports Folder
#        uses: actions/download-artifact@v2
#        with:
#          name: report
#          path: app/build/reports/coverage/androidTest/debug/connected/report.xml

      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: app/build/reports/coverage/androidTest/debug/connected/report.xml
          fail_ci_if_error: true

      - name: Upload Test Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: app/build/reports/kover/reportDebug.xml
          fail_ci_if_error: true

#      - name: Upload Test Report
#        run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/androidTest/debug/connected/report.xml"
#        #
